name       : python-tomli-w
version    : 1.0.0
release    : 2
source     :
    - https://github.com/hukkin/tomli-w/archive/refs/tags/1.0.0.tar.gz : 4fe1fb4696899c01356ef4e028c975103abf62e5fa9472f31f1714100f1b065d
homepage   : https://github.com/hukkin/tomli-w
license    : MIT
component  : programming.python
summary    :
description: |
    A little TOML writer (counterpart to tomli)
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
build      : |
    %python3_setup
install    : |
    %python3_install
